apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: raghad123/goviolin
        resources:
          limits:
            cpu: "300m"
            memory: "150Mi"
        ports:
        - containerPort: 8080    